#!/usr/bin/env bash
# This script configures an Ubuntu server with the below requirements

cp /etc/hosts hosts_tmp
sed -i s/127.*$/127.0.0#!/usr/bin/env bash
# This script configures an Ubuntu server with the below requirements

cp /etc/hosts hosts_tmp
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g hosts_tmp
cp -f hosts_tmp /etc/hosts
